/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PagoResultadoRouteImport } from './routes/pago-resultado'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthUsuariosRouteImport } from './routes/_auth.usuarios'
import { Route as AuthTesoreriaRouteImport } from './routes/_auth.tesoreria'
import { Route as AuthTemplateEditorRouteImport } from './routes/_auth.template-editor'
import { Route as AuthPlanesRouteImport } from './routes/_auth.planes'
import { Route as AuthPerfilRouteImport } from './routes/_auth.perfil'
import { Route as AuthPagosRouteImport } from './routes/_auth.pagos'
import { Route as AuthOnboardingRouteImport } from './routes/_auth.onboarding'
import { Route as AuthEquipoRouteImport } from './routes/_auth.equipo'
import { Route as AuthDocumentosRouteImport } from './routes/_auth.documentos'
import { Route as AuthDefinicionPlanesRouteImport } from './routes/_auth.definicion-planes'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthCalendarioRouteImport } from './routes/_auth.calendario'

const PagoResultadoRoute = PagoResultadoRouteImport.update({
  id: '/pago-resultado',
  path: '/pago-resultado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUsuariosRoute = AuthUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTesoreriaRoute = AuthTesoreriaRouteImport.update({
  id: '/tesoreria',
  path: '/tesoreria',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTemplateEditorRoute = AuthTemplateEditorRouteImport.update({
  id: '/template-editor',
  path: '/template-editor',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPlanesRoute = AuthPlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPerfilRoute = AuthPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPagosRoute = AuthPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEquipoRoute = AuthEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDocumentosRoute = AuthDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDefinicionPlanesRoute = AuthDefinicionPlanesRouteImport.update({
  id: '/definicion-planes',
  path: '/definicion-planes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCalendarioRoute = AuthCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pago-resultado': typeof PagoResultadoRoute
  '/calendario': typeof AuthCalendarioRoute
  '/dashboard': typeof AuthDashboardRoute
  '/definicion-planes': typeof AuthDefinicionPlanesRoute
  '/documentos': typeof AuthDocumentosRoute
  '/equipo': typeof AuthEquipoRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/pagos': typeof AuthPagosRoute
  '/perfil': typeof AuthPerfilRoute
  '/planes': typeof AuthPlanesRoute
  '/template-editor': typeof AuthTemplateEditorRoute
  '/tesoreria': typeof AuthTesoreriaRoute
  '/usuarios': typeof AuthUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pago-resultado': typeof PagoResultadoRoute
  '/calendario': typeof AuthCalendarioRoute
  '/dashboard': typeof AuthDashboardRoute
  '/definicion-planes': typeof AuthDefinicionPlanesRoute
  '/documentos': typeof AuthDocumentosRoute
  '/equipo': typeof AuthEquipoRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/pagos': typeof AuthPagosRoute
  '/perfil': typeof AuthPerfilRoute
  '/planes': typeof AuthPlanesRoute
  '/template-editor': typeof AuthTemplateEditorRoute
  '/tesoreria': typeof AuthTesoreriaRoute
  '/usuarios': typeof AuthUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/pago-resultado': typeof PagoResultadoRoute
  '/_auth/calendario': typeof AuthCalendarioRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/definicion-planes': typeof AuthDefinicionPlanesRoute
  '/_auth/documentos': typeof AuthDocumentosRoute
  '/_auth/equipo': typeof AuthEquipoRoute
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/pagos': typeof AuthPagosRoute
  '/_auth/perfil': typeof AuthPerfilRoute
  '/_auth/planes': typeof AuthPlanesRoute
  '/_auth/template-editor': typeof AuthTemplateEditorRoute
  '/_auth/tesoreria': typeof AuthTesoreriaRoute
  '/_auth/usuarios': typeof AuthUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pago-resultado'
    | '/calendario'
    | '/dashboard'
    | '/definicion-planes'
    | '/documentos'
    | '/equipo'
    | '/onboarding'
    | '/pagos'
    | '/perfil'
    | '/planes'
    | '/template-editor'
    | '/tesoreria'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pago-resultado'
    | '/calendario'
    | '/dashboard'
    | '/definicion-planes'
    | '/documentos'
    | '/equipo'
    | '/onboarding'
    | '/pagos'
    | '/perfil'
    | '/planes'
    | '/template-editor'
    | '/tesoreria'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/pago-resultado'
    | '/_auth/calendario'
    | '/_auth/dashboard'
    | '/_auth/definicion-planes'
    | '/_auth/documentos'
    | '/_auth/equipo'
    | '/_auth/onboarding'
    | '/_auth/pagos'
    | '/_auth/perfil'
    | '/_auth/planes'
    | '/_auth/template-editor'
    | '/_auth/tesoreria'
    | '/_auth/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  PagoResultadoRoute: typeof PagoResultadoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pago-resultado': {
      id: '/pago-resultado'
      path: '/pago-resultado'
      fullPath: '/pago-resultado'
      preLoaderRoute: typeof PagoResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/usuarios': {
      id: '/_auth/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthUsuariosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tesoreria': {
      id: '/_auth/tesoreria'
      path: '/tesoreria'
      fullPath: '/tesoreria'
      preLoaderRoute: typeof AuthTesoreriaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/template-editor': {
      id: '/_auth/template-editor'
      path: '/template-editor'
      fullPath: '/template-editor'
      preLoaderRoute: typeof AuthTemplateEditorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/planes': {
      id: '/_auth/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof AuthPlanesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/perfil': {
      id: '/_auth/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthPerfilRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pagos': {
      id: '/_auth/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof AuthPagosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/equipo': {
      id: '/_auth/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof AuthEquipoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/documentos': {
      id: '/_auth/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthDocumentosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/definicion-planes': {
      id: '/_auth/definicion-planes'
      path: '/definicion-planes'
      fullPath: '/definicion-planes'
      preLoaderRoute: typeof AuthDefinicionPlanesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/calendario': {
      id: '/_auth/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthCalendarioRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCalendarioRoute: typeof AuthCalendarioRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthDefinicionPlanesRoute: typeof AuthDefinicionPlanesRoute
  AuthDocumentosRoute: typeof AuthDocumentosRoute
  AuthEquipoRoute: typeof AuthEquipoRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthPagosRoute: typeof AuthPagosRoute
  AuthPerfilRoute: typeof AuthPerfilRoute
  AuthPlanesRoute: typeof AuthPlanesRoute
  AuthTemplateEditorRoute: typeof AuthTemplateEditorRoute
  AuthTesoreriaRoute: typeof AuthTesoreriaRoute
  AuthUsuariosRoute: typeof AuthUsuariosRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCalendarioRoute: AuthCalendarioRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthDefinicionPlanesRoute: AuthDefinicionPlanesRoute,
  AuthDocumentosRoute: AuthDocumentosRoute,
  AuthEquipoRoute: AuthEquipoRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthPagosRoute: AuthPagosRoute,
  AuthPerfilRoute: AuthPerfilRoute,
  AuthPlanesRoute: AuthPlanesRoute,
  AuthTemplateEditorRoute: AuthTemplateEditorRoute,
  AuthTesoreriaRoute: AuthTesoreriaRoute,
  AuthUsuariosRoute: AuthUsuariosRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  PagoResultadoRoute: PagoResultadoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
